title: Sara Baji
description: MPH Student in Global Epidemiology & Data Science at Emory University
logo: /profile.jpg
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
